model_list: []
router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 600
litellm_settings:
  request_timeout: 600
  drop_params: true
  set_verbose: false
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true
